name       : wayland-protocols
version    : '1.26'
release    : 14
source     :
    - https://gitlab.freedesktop.org/wayland/wayland-protocols/-/archive/1.26/wayland-protocols-1.26.tar.gz : fe56386f436a84e97c3b6a61b76306f205a64425900f247ad0048174b9c32d4d
license    : MIT
homepage   : https://gitlab.freedesktop.org/wayland/wayland-protocols
component  : desktop.wayland
summary    : Wayland Protocols
description: |
    wayland-protocols contains Wayland protocols that adds functionality not available in the Wayland core protocol. Such protocols either adds completely new functionality, or extends the functionality of some other protocol either in Wayland core, or some other protocol in wayland-protocols.
builddeps  :
    - pkgconfig(wayland-scanner)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
