name       : wayland-protocols
version    : 1.0
release    : 1
source     :
    - https://wayland.freedesktop.org/releases/wayland-protocols-1.0.tar.xz : a538a8e3f999f2722897eb60aa2e2b53d879381b413b630957d58a9acd226def
license    : MIT
component  : desktop.wayland
summary    : Wayland Protocols
description: |
    wayland-protocols contains Wayland protocols that adds functionality not
    available in the Wayland core protocol. Such protocols either adds
    completely new functionality, or extends the functionality of some other
    protocol either in Wayland core, or some other protocol in
    wayland-protocols.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
