name       : wayland-protocols
version    : '1.31'
release    : 17
source     :
    - https://gitlab.freedesktop.org/wayland/wayland-protocols/-/archive/1.31/wayland-protocols-1.31.tar.gz : 04d3f66eca99d638ec8dbfdfdf79334290e22028f7d0b04c7034d9ef18a3248a
license    : MIT
homepage   : https://gitlab.freedesktop.org/wayland/wayland-protocols
component  : desktop.wayland
summary    : Wayland Protocols
description: |
    wayland-protocols contains Wayland protocols that adds functionality not available in the Wayland core protocol. Such protocols either adds completely new functionality, or extends the functionality of some other protocol either in Wayland core, or some other protocol in wayland-protocols.
builddeps  :
    - pkgconfig(wayland-scanner)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
